name: ${project.name}
main: ${groupId}.${project.name}
version: "${project.version}"
author: emanon
api-version: 1.13
depend: [ ItemEdit ]
softdepend: [ NBTAPI ]

# Additional info
modrinth-project-id: "dr0F8gew"
modrinth-project-name: "itemtag"
spigot-resource-id: 89634
bstats-plugin-id: 15077
folia-supported: true

commands:
  itemtag:
    description: allows to apply tags to items
    usage: /itemtag
    aliases: [ it ]
  itemtagreload:
    description: reload configurations
    usage: /itemtagreload
  itemtagupdateolditem:
    description: manually update old item
    usage: /itemtagupdateolditem
permissions:
  itemtag.admin:
    default: op
    description: Gives full access to the plugin
    children:
      itemtag.itemtag.*: true
      itemtag.itemtagreload: true
      itemtag.itemtagupdateolditem: true
  itemtag.itemtagupdateolditem:
    default: op
    description: Gives full access to command /itemtagupdateolditem
  itemtag.itemtagreload:
    default: op
    description: Gives full access to command /itemtagreload
  itemtag.itemtag.*:
    default: op
    description: Gives full access to command /itemtag
    children:
      itemtag.itemtag.actions: true
      itemtag.itemtag.effects: true
      itemtag.itemtag.flag: true
      itemtag.itemtag.trigger: true
  itemtag.itemtag.actions:
    default: op
    description: Allow to set actions when using item
  itemtag.itemtag.effects:
    default: op
    description: Allow to add effects for equipped items
  itemtag.itemtag.flag:
    default: op
    description: Allow to add custom flags for items
    children:
      itemtag.itemtag.flag.bypass_clickmove: true
  itemtag.itemtag.flag.bypass_clickmove:
    default: op
    description: Allow to add custom flags for items
  itemtag.itemtag.trigger:
    default: op
    description: Allow to add trigger for equipped items